### ISSUE TITLE
Types not published on npm

### ISSUE THREAD

**Issue by harshal2030** [zerodha/kiteconnectjs#100]
Hey, this repo has types merged 3 weeks ago. when the new release will get published on npm?

**Comment by brayn003** [comment]
Hi, when is the new version getting published?

**Comment by lazuli-admin** [comment]
Hi @vividvilla, any update on this? the types update getting published on npm would be a massive improvement for developer experience

**Comment by anishmitta1** [comment]
Hi @vividvilla, any update on this? the types update getting published on npm would be a massive improvement for developer experience

**Comment by NithinBiliya** [comment]
@vividvilla bump ^

**Comment by ranjanrak** [comment]
@brayn003  @anishmitta1 @NithinBiliya 
There were a couple of refactors needed in ts, and currently in progress. We are reviewing [this refactor MR](https://github.com/zerodha/kiteconnectjs/pull/101). Once that is done, we will publish the new version on npm.

**Comment by ranjanrak** [comment]
@brayn003  @anishmitta1 @NithinBiliya 
The new version with types is published on npm [v5.0.0](https://www.npmjs.com/package/kiteconnect/v/5.0.0). Please refer to the [CHANGELOG](https://github.com/zerodha/kiteconnectjs/blob/master/CHANGELOG.md#kite-v5---typescript) for updates and migration details.
