### ISSUE TITLE
Delay in last_trade_time and timestamp of about 5hrs 30min

### ISSUE THREAD

**Issue by raoulnair** [zerodha/kiteconnectjs#20]
I am using kiteconnectjs version 3.0.0-beta.3 and I am using subscribe() function to fetch the data through websocket.
I found that the last_trade_time and timestamp has delay of about 5:30 Hrs seems its using GST time for calculation.

Below is the data that was received @10:06:20AM
{"tradable":true,"mode":"full","instrument_token":738561,"last_price":1083.3,"last_quantity":33,"average_price":1087.65,"volume":2796789,"buy_quantity":447077,"sell_quantity":420705,"ohlc":{"open":1099.8,"high":1108.9,"low":1073.05,"close":1099.8},"change":-1.5002727768685216,"last_trade_time":"2018-07-16T04:36:19.000Z","timestamp":"2018-07-16T04:36:20.000Z","oi":0,"oi_day_high":0,"oi_day_low":0,"depth":{"buy":[{"quantity":67,"price":1083.4,"orders":1},{"quantity":379,"price":1083.15,"orders":5},{"quantity":5,"price":1083,"orders":1},{"quantity":12,"price":1082.9,"orders":1},{"quantity":118,"price":1082.85,"orders":2}],"sell":[{"quantity":527,"price":1083.5,"orders":5},{"quantity":100,"price":1083.55,"orders":2},{"quantity":350,"price":1083.6,"orders":1},{"quantity":2,"price":1083.75,"orders":1},{"quantity":25,"price":1083.8,"orders":1}]}}

Do I need to manually convert respective fields to IST time or the API will take care of the same.

Thanks

**Comment by vividvilla** [comment]
If you running this in a server or system in UTC then you will get all dates in UTC time.

**Comment by Aravin** [comment]
It is not an issue. It is UTC time. Even I though it was issue. 

Why I converted it using console window I got this:

![image](https://user-images.githubusercontent.com/4869265/61998462-33c7e280-b0ce-11e9-976b-ecef63c1adbc.png)

**Comment by vividvilla** [comment]
We don't handle timezone while converting incoming timestamp from upstream (which is in IST). So if your local timezone is in IST then it will just parse the timestamp and show the timezone as IST.
