### ISSUE TITLE
Some APIs are not working margins, profiles etc

### ISSUE THREAD

**Issue by Aravin** [zerodha/kiteconnectjs#23]
**Some APIs are not working margins, profiles etc.**

**Code**: Same for instruments & all other APIs
![image](https://user-images.githubusercontent.com/4869265/62319761-5ab25a00-b4bc-11e9-8959-ddc7218c29a4.png)

_**Instrument API - working**_
![image](https://user-images.githubusercontent.com/4869265/62319772-5ede7780-b4bc-11e9-9d57-675d0a87e70c.png)

_**Profile: (not working)**_
![image](https://user-images.githubusercontent.com/4869265/62319804-6e5dc080-b4bc-11e9-90c9-645f2299d9f1.png)

it was working yesterday. I didn't changed anything in code.

I am using Javascript SDK.

**Comment by Aravin** [comment]
why it was closed without any comment?

**Comment by vividvilla** [comment]
@Aravin we either send error response in case of error or the actual response in defined structure (as per docs). So its not possible for this to happen in lib, if you want to verify that you can run the examples we have provided here with your access token and api_key - https://github.com/zerodha/kiteconnectjs/blob/master/examples/connect.js
