### ISSUE TITLE
Postback data in Ticker API

### ISSUE THREAD

**Issue by ameyakarve** [zerodha/kiteconnectjs#30]
Per https://kite.trade/docs/connect/v3/websocket/ , postbacks for trade events should be available, but I see no documentation in the Node client for this

Also, the postback documentation does not contain the order tag. Will this be supplied as well?

**Comment by ameyakarve** [comment]
The data is available, but the documentation was missing. Let me know if you want me to send a PR

**Comment by ranjanrak** [comment]
All event callbacks are already documented under `on` events. Refer [here](https://kite.trade/docs/kiteconnectjs/v3/KiteTicker.html#on).
