### ISSUE TITLE
Use let not var

### ISSUE THREAD

**Issue by aymanapatel** [zerodha/kiteconnectjs#34]
Looking at README, I instantly noticed that the doc is using `var` keyword for variables. 

Example:

```javascript
var KiteTicker = require("kiteconnect").KiteTicker;
var ticker = new KiteTicker({
	api_key: "api_key",
	access_token: "access_token"
});
```

According to conformance with ECMAScript standard, it would be better if we were to use `let` not `var` keyword. 

Was it not enforced due to breaking changes?
If not, I can raise a PR to update the documentation. 😄

**Comment by vividvilla** [comment]
The lib itself was written in ES5 so that's why `var` has been used everywhere. We have planned a rewrite in `ESx` soon which will sort this out.
