### ISSUE TITLE
getLTP is not working in 3.2.0

### ISSUE THREAD

**Issue by sunilgautam** [zerodha/kiteconnectjs#40]
getLTP function is returning undefined in v3.2.0

```
const ltpResponse = await kiteConnect.getLTP([
  'NSE:NIFTY BANK',
  'BSE:SENSEX',
]);
```

Above snippet returning proper data in v3.1.0 whereas same returning `undefined` in v3.2.0.
After setting debug true in both versions i can see there is difference between request query string.

v3.1.0 => /quote/ltp?i=NSE%3ANIFTY%20BANK&i=BSE%3ASENSEX
v3.2.0 => /quote/ltp?i[]=NSE:NIFTY+BANK&i[]=BSE:SENSEX

Node: v14.4.0

**Comment by vividvilla** [comment]
Thanks for reporting, this just got patched and released as `kiteconnect@3.2.1`.
