### ISSUE TITLE
npm audit report shows 2 high severity issues

### ISSUE THREAD

**Issue by kp666** [zerodha/kiteconnectjs#47]
axios  <=0.21.0
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
Denial of Service - https://npmjs.com/advisories/880

papaparse  <5.2.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1515

can be fixed by npm audit fix

**Comment by ranjanrak** [comment]
The above-mentioned dependencies are already updated. There is no vulnerability as of now.
```{
  "auditReportVersion": 2,
  "vulnerabilities": {},
  "metadata": {
    "vulnerabilities": {
      "info": 0,
      "low": 0,
      "moderate": 0,
      "high": 0,
      "critical": 0,
      "total": 0
    },
   .....
  }
}```
