### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by rajendrasp** [zerodha/kiteconnectjs#57]
Hi,
Do you plan to provide type definitions anytime soon?
Also there is a unofficial library written in TypeScript - https://github.com/anurag2pirad/kiteconnect-ts
Would you validate it for use by us?
Thanks

**Comment by ContraHacker** [comment]
Would love to have official TypeScript support.

**Comment by apoorvmote** [comment]
Yes awaiting eagerly for Typescript support.

**Comment by vividvilla** [comment]
@ranjanrak

**Comment by anurag-roy** [comment]
Hey @vividvilla @ranjanrak,

I am curious as to what direction the you guys want to take the project in terms of TypeScript
- no TypeScript
- only d.ts files
- types in the DefinitelyTyped repo as `@types/kiteconnectjs`
- full rewrite in TypeScript

@bhavyasf has made good progress in terms of a ts rewrite (#88) and I am also ready to contribute if the direction is made clear. ( I have a .d.ts PR almost ready!)

Thanks!

**Comment by ranjanrak** [comment]
Hi @GargDivanshu 
> then now addition of types and interface is left in the codebase

This task is being actively worked on by @bhavya3024. You can track the progress of this task by following issue #96
