### ISSUE TITLE
Any plans to add in typescript types?

### ISSUE THREAD

**Issue by darwin403** [zerodha/kiteconnectjs#65]
Hi, there is any plan to add the typescript types. If not I may consider doing it sometime if its alright.

Please do list out some additional critereon for listing it as `@types/kiteconnect`

**Comment by ranjanrak** [comment]
Hey @darwin403 
Yes, you can add types and create a PR, we will review and release it as `@types/kiteconnect`. You can refer to the [kiteconnect doc](https://kite.trade/docs/connect/v3/) to know all response types.

**Comment by vividvilla** [comment]
Duplicate #57
