### ISSUE TITLE
react native support

### ISSUE THREAD

**Issue by abhiilash** [zerodha/kiteconnectjs#98]
is this sdk support react native?

**Comment by ranjanrak** [comment]
You will encounter CORS issues when making requests from a React Native app to the Kite Connect API, as the API is designed to restrict third-party apps from displaying its data, as per [data usage policy](https://kite.trade/terms/).

**Comment by Gauravk26** [comment]
I want to make react app in which i can place order , but i am getting cors error, then I made one nodes js server in which i have integrated kite connect and then calling the api from my react api ,but for that i have to use setinterval to call in every 500ms , **_Is there any way to recieve data as soons as we are updating data in node js with help of Ticker_**

**Comment by abhiilash** [comment]
Yes you can use websocket
